spring:
  application:
    name: template-spring-batch

  # Configuração do PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_batch
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    platform: postgresql

  # Executa schema.sql e data.sql automaticamente
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  # Configuração do Spring Batch
  batch:
    jdbc:
      initialize-schema: always
      table-prefix: BATCH_
    job:
      enabled: false

# Configuração de logging
logging:
  level:
    org.springframework.batch: DEBUG
    org.springframework.batch.core: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
    com.alelo: DEBUG
